### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by ogata2606** [lsw9021/MASS#12]
Hi, thank you for providing the code.
I could "Run Training". But, I cannot "Run UI" or "Run Trained data" etc...
Here is the error message. Maybe this is a numpy version problem...
Could you tell me what version do you use?

`./render/render ../data/metadata.txt`
`Human(DOFs : 56)`
`Ground(DOFs : 0)`
`RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa`
`terminate called after throwing an instance of 'boost::python::error_already_set'`

Thank you

**Comment by lsw9021** [comment]
Hi, I'm currently using numpy version 1.15.4.

Maybe the problem came from the CUDA.
The attached link may solve the problem.

https://github.com/lsw9021/MASS/issues/11

Thank you.

**Comment by ogata2606** [comment]
hmm...
I don't think it is not CUDA problem.
I have CUDA environment.
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```

**Comment by ogata2606** [comment]
I solved this problem.
I reinstalled boost, the program was moved!

Thank you!
