### ISSUE TITLE
What Python version

### ISSUE THREAD

**Issue by orsolli** [lsw9021/MASS#13]
You specify boost version and dart version, but not python version.
I've tried 3.7m, 3.7.4, 3.6.9, 3.3.6, but no luck.
I found out that I had to install python --without-pymalloc. Boost is using _PyUnicode_AsString() which is removed in a version of 3.3, I think, but virtualenv is problematic in these early versions of python3.

**Comment by mulkkyul** [comment]
I'm running the code with Python 3.5.2.

**Comment by orsolli** [comment]
I think the problem was in my system. It needed a complete reinstall anyway.

But I ended up running the whole thing in Docker anyway
