### ISSUE TITLE
How to produce custom motions using MotionBuilder?

### ISSUE THREAD

**Issue by meaten** [lsw9021/MASS#18]
Hi! Thanks for sharing the great work!

Could you share the .fbx file you used with us or tell us the right way to retarget custom motions to your musculoskeletal model using MotionBuilder?
Thanks!

**Comment by meaten** [comment]
Any suggestions?

**Comment by lsw9021** [comment]
I just uploaded the Maya file and the .fbx file for retargeting.
Please find the files in data/maya.

Thank you!

**Comment by meaten** [comment]
Thank you very much! I appreciate it very much:)
