### ISSUE TITLE
Unable to execute cmake .. to install/compile MASS

### ISSUE THREAD

**Issue by ThiagoBGL** [lsw9021/MASS#27]
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find DART (missing: collision-bullet)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/dart/cmake/DARTConfig.cmake:174 (find_package_handle_standard_args)
  core/CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!

I tried reinstall DART with all forms, collision-bullet was install

**Comment by Xianjin111** [comment]
> CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message): Could NOT find DART (missing: collision-bullet) Call Stack (most recent call first): /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE) /usr/local/share/dart/cmake/DARTConfig.cmake:174 (find_package_handle_standard_args) core/CMakeLists.txt:9 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> 
> I tried reinstall DART with all forms, collision-bullet was install

Have you solved the problems? THX
