### ISSUE TITLE
How to Train for a successful backflip？

### ISSUE THREAD

**Issue by Authur-Morgan** [lsw9021/MASS#38]
My backflip only works as a jump

**Comment by todayThursday** [comment]
> 我的后空翻只能用作跳跃

I have been training the running model recently, but no matter how to modify reward_param, the training effect is not good, I want to know if you have solved this problem, but on the other hand, I think the weight parameter of the reward function does not affect the effect of the training model, in the code, The reward function only considers the position error and the velocity error of the joint, and scales these two with the error of the end-effector. Logically, if we only consider the similarity of the motion, and do not need to add other effects, just the results of the training of the neural network, then why does the run model not have good results no matter how it is felt
