### ISSUE TITLE
Could you describe the process of model creation?

### ISSUE THREAD

**Issue by yurket** [lsw9021/MASS#8]
Hi, Lee Seung Hwan!
Thanks for a cool paper and code! Could you please describe a process of model and muscles creation a bit more? E.g. how did you create `human.xml` and `muscle284.xml` files? Is there a GUI helper?
Thanks!

**Comment by lsw9021** [comment]
Hi Minsk,

We manually find the set of points which represent the geometry of the muscles as close as possible. 
The process was done in Maya. With the set of points, we made the xml file using simple xml parsing library such as TinyXML.

The link below is my previous git page, which has the code for the parsing.

https://github.com/snumrl/MSS

In the xmlparser folder, you can find the parsing code which takes the 3D positions of the points and the muscle properties and generate the xml file. The corresponding data can be found in character/txt_segment3/ folder.

**Comment by yurket** [comment]
Thanks!
